### ISSUE TITLE
Support promise cancelation out of the box with observables

### ISSUE THREAD

**Issue by Kaltsoon** [async-library/react-async#164]
Right now promise cancelation requires the use of `AbortController`, which requires the users of the library to handle the cancelation themselves. Could we eliminate the race conditions caused by the missing cancelation mechanism using observables without introducing any breaking changes?

We could turn a promise into an observable:

```javascript
const observableFromPromise = promise => {
  return new Observable(observer => {
    promise
      .then(data => {
        observer.next({ data });
        observer.complete();
      })
      .catch(error => {
        observer.next({ error });
        observer.complete();
      });
  });
};
```

And then subscribe to it:

```javascript
const subscription = observableFromPromise(promise).subscribe(({ data, error }) => {
  // Update the state
});
```

Cleanup would be as simple as:

```javascript
if (subscription) {
  subscription.unsubscribe();
}
```

This solution would eliminate the race conditions which are present when a developer forgets or doesn't know how to use the `AbortController`.

**Comment by ghengeveld** [comment]
First of all, the AbortController is completely optional. If the browser doesn't support it, React Async will not use it. To prevent race conditions, we have our own cancellation mechanism which is based on a counter. When a new promise starts, we increment the counter, and when one finishes, we check if the counter still has the same value.

I'm intrigued by your suggestion to use an Observable. This is something I've been considering in order to support subscriptions / websockets. However, as far as I know there currently is no such thing in vanilla JavaScript, and I don't want to introduce a dependency on e.g. RxJS.

**Comment by Kaltsoon** [comment]
Great, didn't read the source code closely enough to notice this mechanism. It's true, observable is currently only [at stage 1](https://tc39.es/proposal-observable/) and we would require a dependency such as [zen-observable](https://github.com/zenparsing/zen-observable) (which is very light weight). 

I'll close this issue because the race condition issue isn't present.
