### ISSUE TITLE
Is it possible to use this library with web workers?

### ISSUE THREAD

**Issue by harrybiddle** [async-library/react-async#257]
Hello! Thank you for the library, it's a very nice API and the documentation is fantastic.

After using the library I realised that since my async task is entirely CPU, promises aren't appropriate and I would need to use web workers instead.

Is library a good fit for web workers, or should I look somewhere else? Does anybody have a code snippet where they use react-async with web workers?

Thank you

**Comment by ghengeveld** [comment]
Hi Harry,

Happy you ask, because I actually developed [React WebWorker](https://github.com/async-library/react-webworker) before building React Async. However it does not provide a hook and had less features in general.

We actually have [plans](https://github.com/async-library/future/issues/3) for a future version of React Async to support subscriptions, which would allow it to be used with a Web Worker. There's work-in-progress which [supports subscriptions](https://github.com/async-library/future/blob/core/src/service.test.js#L139), but can't find the time to wrap that up into something shippable.

**Comment by harrybiddle** [comment]
That looks great, I'll give it a go :). I am using create-react-app and since posting I also experimented with [workerize-loader](https://github.com/developit/workerize-loader). I'm not sure if it's best practice but the code snippet below seems to work:

```javascript
// eslint-disable-next-line import/no-webpack-loader-syntax
import worker from "workerize-loader!../../worker";

function dispatch({ myArg }) {
  let inst = worker();
  return inst.myFunction(myArg);
}

export default function MyComponent() {
  myArg= ... ;
  const { data, error, isPending } = useAsync({
    promiseFn: dispatch,
    myArg: myArg
  });
  ...
}
```

**Comment by harrybiddle** [comment]
Hey guys - don't want to clutter up your open issues, and my question is answered and problem resolved. Hopefully this thread is useful for others who come across it - closing out
