### ISSUE TITLE
Passing a `useState` value as a prop into Async's promiseFn doesn't invoke the promiseFn

### ISSUE THREAD

**Issue by alanbuchanan** [async-library/react-async#259]
According to the [docs](https://docs.react-async.com/api/options#promisefn);

> If you need to pass variables to the promiseFn, pass them as additional props to <Async>, as promiseFn will be invoked with these props.

Going on this, I would think I can pass in a `useState` stateful value as a prop into an Async component when using the [compounds to Async](https://docs.react-async.com/getting-started/usage#as-compounds-to-less-than-async-greater-than) approach.

However, the `promiseFn` doesn't get invoked when that stateful value changes. Please see my small example: https://codesandbox.io/s/heuristic-wood-74591 - it's an input field which queries the GitHub Users API when the form is submitted, and should return data about a user.

When the `fUsername` value changes, I would expect the `promiseFn` to run.

Perhaps I am misunderstanding something?

I can make this work by moving the `promiseFn` - wrapped in `React.useCallback` - inside the consuming component. But I'd like to know why I can't make it work for the way which involves using a function outside the component.

**Comment by ghengeveld** [comment]
You're correctly passing props to `promiseFn`, however we don't watch for changes to those props automatically because oftentimes that's undesired (and could lead to infinite loops). If you want to trigger a new invocation of `promiseFn` when a value changes, you can use `watch` or `watchFn`. Probably passing `watch={fUsername}` is all you need.
