### ISSUE TITLE
Support for async iterators

### ISSUE THREAD

**Issue by RangerMauve** [async-library/react-async#276]
This library has been super helpful for loading data needed for various views in an app.

However, we've run into issues when it came to integrating asynchronous updates with everything.

It'd be cool if `promiseFN` could be extended with `generatorFN` which would be an async generator that would yield new `data` for the component to render and have react-async manage spinning it up and tearing it down.

Does this sound like it should belong in this library, or would it be better to spin out something new for this use case?

**Comment by ghengeveld** [comment]
Hey, this is not currently supported by React Async, but it's part of the [future plans](https://github.com/async-library/future/issues/3). In fact there's a working implementation of [subscriptions](https://github.com/async-library/future/blob/2b6c5a9292217f0ed0b118ec40e43361dbfa1364/src/service.test.js#L139-L159) in an unreleased future version of the library. However, work on this is currently stalled, mostly due to uncertainty around Suspense and the appearance of React Query and SWR. Also React Async is currently implemented in TypeScript while this future version is in vanilla JS, and I'm not a TypeScript expert at all (I didn't do the migration to TS myself). So if you'd like to pick up the effort to get it into a shippable state (it's mostly feature complete already), I'd really really appreciate it. If not then this is probably going to take a while for me to get back to.

**Comment by RangerMauve** [comment]
Thanks for the response! I actually ended up migrating to [use-async-generator](https://www.npmjs.com/package/use-async-generator) since it ended up fulfilling all my use cases with less overall code. 😅

**Comment by ghengeveld** [comment]
Fair enough. Enjoy.
