### ISSUE TITLE
Retrieving headers on failed request

### ISSUE THREAD

**Issue by Eli-Black-Work** [async-library/react-async#311]
Hello 🙂

Is there any way to retrieve headers on a failed request? I'm utilizing `useFetch` to do a POST to an authentication server. The POST fails with the code `net::ERR_FAILED` but _also_ returns valuable headers.

I've tried retrieving the headers by accessing the `data.error.response.headers` property, but it looks like `data.error.response` is `null` when the request has failed with `net::ERR_FAILED` instead of via a response code (such as `500` or `401`).

Thanks 🙂

**Comment by ghengeveld** [comment]
I can't make this out from context, but possibly you're looking for `error.response` rather than `data.error.response`.

If not, this sounds like a bug. Right now we use [`response.ok`](https://github.com/async-library/react-async/blob/24062757bb7570434ef1022b1f0aa07a33552377/packages/react-async/src/useAsync.tsx#L252) to test for error responses. Can you provide more info about the exact response? You say it includes valuable headers, which leads me to think it _should_ have a status code as well, and thus properly set `response.ok`. More likely it just doesn't get a response at all. I suspect it just doesn't reach `parseResponse`, but instead the promise rejects. What the rejection value will be, I have no idea. Can you inspect the value of `error` (not `data.error`)?

**Comment by Eli-Black-Work** [comment]
Thanks for the reply, and for leaving this open, @ghengeveld 🙂

I don't think I'll be able to follow up on this in the immediate future, because our project ended up not using `react-async`, so I'll go ahead and close this.

Thanks again 🙂
