### ISSUE TITLE
promiseFn is not a function

### ISSUE THREAD

**Issue by sam13591980** [async-library/react-async#313]
Hello everyone!
Any one get promiseFn is not a function ?
If I use <Async promise ... it does not give the above error and also works from loading JSX perspective (<Async.Fulfilled>) but it does not update the DOM

**Comment by ghengeveld** [comment]
You'll have to provide more context and code, because this is very little to go on. I'm not sure whether you want to use the `<Async promiseFn={...}>` syntax or the hook. I recommend you take a look at the [guide](https://docs.react-async.com/guide/async-components) section of the docs.

Feel free to reopen if necessary.
